`timescale 1ns/1ps

// ============================================================================
// Stage13.12
// Top-level functional testbench for systolic_top.
//
// Verification boundary:
//   * A/B stimulus and C golden values are generated by Python.
//   * SystemVerilog does NOT calculate GEMM golden results.
//   * DUT interaction uses only the frozen Stage13.9 Rev.B top-level ports.
//   * No hierarchical DUT/debug signal is referenced.
//   * TB is responsible only for:
//       - loading row-major Python vectors,
//       - arranging A/B data into the frozen S=32 tiled FIFO stream order,
//       - driving top-level FIFO interfaces,
//       - comparing top-level result data against Python golden values.
//
// Frozen Stage13.12 case:
//   M = 256, K = 108, N = 64, S = 32
//
// Python command example:
//   python generate_systolic_golden.py \
//       --outdir vectors \
//       --name case_stage13_12 \
//       --m 256 --k 108 --n 64
//
// Simulation plusargs (optional):
//   +VECTOR_DIR=<directory>   default: vectors
//   +CASE_NAME=<prefix>       default: case_stage13_12
// ============================================================================

module tb_systolic_top;

    parameter int DATA_WIDTH     = 32;
    parameter int ACC_WIDTH      = 71;
    parameter int S_MAX          = 32;
    parameter int MAX_M          = 256;
    parameter int MAX_K          = 108;
    parameter int MAX_N          = 64;
    parameter int IN_FIFO_DEPTH  = 128;
    parameter int OUT_FIFO_DEPTH = 64;
    parameter int TEST_TIMEOUT   = 5_000_000;

    parameter int CASE_M = 256;
    parameter int CASE_K = 108;
    parameter int CASE_N = 64;
    parameter int CASE_S = 32;

    parameter int A_WORDS = CASE_M * CASE_K;
    parameter int B_WORDS = CASE_K * CASE_N;
    parameter int C_WORDS = CASE_M * CASE_N;

    typedef logic signed [DATA_WIDTH-1:0] data_t;
    typedef logic signed [ACC_WIDTH-1:0]  acc_t;

    // ------------------------------------------------------------------------
    // DUT top-level interface only
    // ------------------------------------------------------------------------
    logic i_clk;
    logic i_rst_n;
    logic i_start;

    logic [$clog2(MAX_M+1)-1:0] i_m_size;
    logic [$clog2(MAX_K+1)-1:0] i_k_size;
    logic [$clog2(MAX_N+1)-1:0] i_n_size;

    logic [S_MAX-1:0] i_a_wren;
    data_t            i_a_wdata [S_MAX];
    logic [S_MAX-1:0] o_a_full;

    logic [S_MAX-1:0] i_b_wren;
    data_t            i_b_wdata [S_MAX];
    logic [S_MAX-1:0] o_b_full;

    logic i_result_rden;
    acc_t o_result_data;
    logic o_result_data_vld;
    logic o_result_empty;
    logic o_result_full;

    logic o_busy;
    logic o_done;
    logic o_cfg_error;

    systolic_top #(
        .DATA_WIDTH     (DATA_WIDTH),
        .ACC_WIDTH      (ACC_WIDTH),
        .S_MAX          (S_MAX),
        .MAX_M          (MAX_M),
        .MAX_K          (MAX_K),
        .MAX_N          (MAX_N),
        .IN_FIFO_DEPTH  (IN_FIFO_DEPTH),
        .OUT_FIFO_DEPTH (OUT_FIFO_DEPTH)
    ) dut (
        .i_clk              (i_clk),
        .i_rst_n            (i_rst_n),
        .i_start            (i_start),
        .i_m_size           (i_m_size),
        .i_k_size           (i_k_size),
        .i_n_size           (i_n_size),
        .i_a_wren           (i_a_wren),
        .i_a_wdata          (i_a_wdata),
        .o_a_full           (o_a_full),
        .i_b_wren           (i_b_wren),
        .i_b_wdata          (i_b_wdata),
        .o_b_full           (o_b_full),
        .i_result_rden      (i_result_rden),
        .o_result_data      (o_result_data),
        .o_result_data_vld  (o_result_data_vld),
        .o_result_empty     (o_result_empty),
        .o_result_full      (o_result_full),
        .o_busy             (o_busy),
        .o_done             (o_done),
        .o_cfg_error        (o_cfg_error)
    );

    // ------------------------------------------------------------------------
    // Python-generated vectors, loaded exactly in row-major order.
    //
    // A index = m*CASE_K + k
    // B index = k*CASE_N + n
    // C index = m*CASE_N + n
    // ------------------------------------------------------------------------
    data_t matrix_a_flat [A_WORDS];
    data_t matrix_b_flat [B_WORDS];
    acc_t  golden_c_flat [C_WORDS];

    // Software queues are scheduling objects only. They never calculate golden.
    data_t a_stream_q [S_MAX][$];
    data_t b_stream_q [S_MAX][$];
    acc_t  expected_q[$];

    string vector_dir;
    string case_name;
    string a_hex_path;
    string b_hex_path;
    string golden_hex_path;

    int total_errors;
    int result_count;
    int done_count;
    int a_feed_count [S_MAX];
    int b_feed_count [S_MAX];

    longint unsigned expected_a_writes;
    longint unsigned expected_b_writes;
    longint unsigned accepted_a_writes;
    longint unsigned accepted_b_writes;

    bit feeder_enabled;
    bit reader_enabled;
    bit test_active;
    bit seen_done;
    bit seen_busy;

    // ------------------------------------------------------------------------
    // Clock
    // ------------------------------------------------------------------------
    always #5 i_clk = ~i_clk;

    function automatic int min_int(input int lhs, input int rhs);
        min_int = (lhs < rhs) ? lhs : rhs;
    endfunction

    task automatic report_error(input string message);
        begin
            total_errors++;
            $error("[Stage13.12] %s", message);
        end
    endtask

    task automatic check_file_exists(input string path);
        integer fd;
        begin
            fd = $fopen(path, "r");
            if (fd == 0)
                $fatal(1, "[Stage13.12] vector file not found: %s", path);
            $fclose(fd);
        end
    endtask

    task automatic apply_reset;
        begin
            test_active        = 1'b0;
            feeder_enabled     = 1'b0;
            reader_enabled     = 1'b0;
            i_start            = 1'b0;
            i_result_rden      = 1'b0;
            i_a_wren           = '0;
            i_b_wren           = '0;
            i_rst_n            = 1'b0;

            repeat (4) @(posedge i_clk);
            @(negedge i_clk);
            i_rst_n = 1'b1;
            repeat (2) @(posedge i_clk);
        end
    endtask

    // ------------------------------------------------------------------------
    // Load Python-generated A/B/C files.
    // No SV-side matrix generation and no SV-side GEMM calculation.
    // ------------------------------------------------------------------------
    task automatic load_python_vectors;
        begin
            a_hex_path      = {vector_dir, "/", case_name, "_A.hex"};
            b_hex_path      = {vector_dir, "/", case_name, "_B.hex"};
            golden_hex_path = {vector_dir, "/", case_name, "_golden.hex"};

            check_file_exists(a_hex_path);
            check_file_exists(b_hex_path);
            check_file_exists(golden_hex_path);

            $display("[Stage13.12] Loading A      : %s", a_hex_path);
            $display("[Stage13.12] Loading B      : %s", b_hex_path);
            $display("[Stage13.12] Loading golden : %s", golden_hex_path);

            $readmemh(a_hex_path,      matrix_a_flat);
            $readmemh(b_hex_path,      matrix_b_flat);
            $readmemh(golden_hex_path, golden_c_flat);
        end
    endtask

    // ------------------------------------------------------------------------
    // Build the frozen Stage13.12 execution stream.
    //
    // Tile order:
    //   M-tile -> N-tile
    //
    // Within each tile:
    //   A lane r : A[mb+r][k], k=0..K-1
    //   B lane c : B[k][nb+c], k=0..K-1
    //
    // Expected result order:
    //   M-tile -> N-tile -> local row -> local col
    //
    // Golden values themselves always come from Python-generated C.hex.
    // ------------------------------------------------------------------------
    task automatic build_reference_streams;
        int rows;
        int cols;
        int a_index;
        int b_index;
        int c_index;
        begin
            expected_q.delete();
            expected_a_writes = 0;
            expected_b_writes = 0;

            for (int lane = 0; lane < S_MAX; lane++) begin
                a_stream_q[lane].delete();
                b_stream_q[lane].delete();
                a_feed_count[lane] = 0;
                b_feed_count[lane] = 0;
            end

            for (int mb = 0; mb < CASE_M; mb += CASE_S) begin
                for (int nb = 0; nb < CASE_N; nb += CASE_S) begin
                    rows = min_int(CASE_S, CASE_M - mb);
                    cols = min_int(CASE_S, CASE_N - nb);

                    for (int r = 0; r < rows; r++) begin
                        for (int k = 0; k < CASE_K; k++) begin
                            a_index = (mb + r) * CASE_K + k;
                            a_stream_q[r].push_back(matrix_a_flat[a_index]);
                            expected_a_writes++;
                        end
                    end

                    for (int c = 0; c < cols; c++) begin
                        for (int k = 0; k < CASE_K; k++) begin
                            b_index = k * CASE_N + (nb + c);
                            b_stream_q[c].push_back(matrix_b_flat[b_index]);
                            expected_b_writes++;
                        end
                    end

                    for (int r = 0; r < rows; r++) begin
                        for (int c = 0; c < cols; c++) begin
                            c_index = (mb + r) * CASE_N + (nb + c);
                            expected_q.push_back(golden_c_flat[c_index]);
                        end
                    end
                end
            end

            if (expected_q.size() != C_WORDS)
                $fatal(1,
                    "[Stage13.12] internal scheduling error: expected_q=%0d C_WORDS=%0d",
                    expected_q.size(), C_WORDS);
        end
    endtask

    // A-side host feeder. Flow control uses only the formal o_a_full interface.
    task automatic a_fifo_driver;
        begin
            forever begin
                @(negedge i_clk);
                i_a_wren = '0;

                for (int lane = 0; lane < S_MAX; lane++) begin
                    i_a_wdata[lane] = '0;

                    if (i_rst_n && feeder_enabled &&
                        !o_a_full[lane] &&
                        (a_stream_q[lane].size() != 0)) begin
                        i_a_wren[lane]  = 1'b1;
                        i_a_wdata[lane] = a_stream_q[lane].pop_front();
                        a_feed_count[lane]++;
                    end
                end
            end
        end
    endtask

    // B-side host feeder. Flow control uses only the formal o_b_full interface.
    task automatic b_fifo_driver;
        begin
            forever begin
                @(negedge i_clk);
                i_b_wren = '0;

                for (int lane = 0; lane < S_MAX; lane++) begin
                    i_b_wdata[lane] = '0;

                    if (i_rst_n && feeder_enabled &&
                        !o_b_full[lane] &&
                        (b_stream_q[lane].size() != 0)) begin
                        i_b_wren[lane]  = 1'b1;
                        i_b_wdata[lane] = b_stream_q[lane].pop_front();
                        b_feed_count[lane]++;
                    end
                end
            end
        end
    endtask

    // Host result reader. Uses only o_result_empty and i_result_rden.
    task automatic output_reader;
        begin
            forever begin
                @(negedge i_clk);
                i_result_rden = 1'b0;

                if (i_rst_n && reader_enabled && !o_result_empty)
                    i_result_rden = 1'b1;
            end
        end
    endtask

    // ------------------------------------------------------------------------
    // Top-level-only scoreboard.
    // A comparison happens only when the result FIFO reports data valid.
    // ------------------------------------------------------------------------
    always @(posedge i_clk) begin
        if (i_rst_n && test_active && o_result_data_vld) begin
            acc_t expected;

            if (expected_q.size() == 0) begin
                report_error($sformatf(
                    "unexpected extra output[%0d] = %0d",
                    result_count, $signed(o_result_data)));
            end
            else begin
                expected = expected_q.pop_front();

                if ($signed(o_result_data) !== $signed(expected)) begin
                    report_error($sformatf(
                        "result[%0d] got %0d expected %0d",
                        result_count,
                        $signed(o_result_data),
                        $signed(expected)));
                end
            end

            result_count++;
        end
    end

    // ------------------------------------------------------------------------
    // Top-level protocol/activity monitor only.
    // ------------------------------------------------------------------------
    always @(posedge i_clk) begin
        int writes_this_cycle;

        if (i_rst_n) begin
            if ($isunknown({o_busy, o_done, o_cfg_error,
                            o_a_full, o_b_full,
                            o_result_data_vld, o_result_empty, o_result_full}))
                report_error("X/Z detected on a top-level control signal");

            if (test_active) begin
                if (o_busy)
                    seen_busy = 1'b1;

                if (o_cfg_error)
                    report_error("unexpected o_cfg_error");

                if (o_done) begin
                    done_count++;
                    seen_done = 1'b1;

                    if (done_count > 1)
                        report_error("o_done asserted more than once");
                end
            end

            writes_this_cycle = 0;
            for (int lane = 0; lane < S_MAX; lane++) begin
                if (i_a_wren[lane]) begin
                    writes_this_cycle++;
                    if (o_a_full[lane])
                        report_error($sformatf(
                            "A write attempted while lane %0d full", lane));
                end
            end
            accepted_a_writes += writes_this_cycle;

            writes_this_cycle = 0;
            for (int lane = 0; lane < S_MAX; lane++) begin
                if (i_b_wren[lane]) begin
                    writes_this_cycle++;
                    if (o_b_full[lane])
                        report_error($sformatf(
                            "B write attempted while lane %0d full", lane));
                end
            end
            accepted_b_writes += writes_this_cycle;
        end
    end

    // ------------------------------------------------------------------------
    // Stage13.12 test sequence
    // ------------------------------------------------------------------------
    initial begin
        int wait_cycles;
        int errors_at_start;
        bit first_tile_preloaded;

        i_clk               = 1'b0;
        i_rst_n             = 1'b0;
        i_start             = 1'b0;
        i_m_size            = '0;
        i_k_size            = '0;
        i_n_size            = '0;
        i_a_wren            = '0;
        i_b_wren            = '0;
        i_result_rden       = 1'b0;
        feeder_enabled      = 1'b0;
        reader_enabled      = 1'b0;
        test_active         = 1'b0;
        seen_done           = 1'b0;
        seen_busy           = 1'b0;
        total_errors        = 0;
        result_count        = 0;
        done_count          = 0;
        accepted_a_writes   = 0;
        accepted_b_writes   = 0;

        vector_dir = "D:/ai_ic_project/vscode/ic_lab03_systolic_array/tb/golden/vectors";
        case_name  = "case_stage13_12";
        void'($value$plusargs("VECTOR_DIR=%s", vector_dir));
        void'($value$plusargs("CASE_NAME=%s", case_name));

        for (int lane = 0; lane < S_MAX; lane++) begin
            i_a_wdata[lane] = '0;
            i_b_wdata[lane] = '0;
        end

        $display("\n============================================================");
        $display(" Stage13.12 systolic_top functional verification");
        $display(" M=%0d K=%0d N=%0d S=%0d", CASE_M, CASE_K, CASE_N, CASE_S);
        $display(" Python golden only; no SV GEMM calculation");
        $display("============================================================\n");

        load_python_vectors();
        build_reference_streams();
        errors_at_start = total_errors;

        fork
            a_fifo_driver();
            b_fifo_driver();
            output_reader();
        join_none

        apply_reset();

        @(negedge i_clk);
        i_m_size       = CASE_M;
        i_k_size       = CASE_K;
        i_n_size       = CASE_N;
        feeder_enabled = 1'b1;
        reader_enabled = 1'b1;

        // Preload one complete first SxS tile before i_start.
        // For the frozen S=32 case this means K words on every active A/B lane.
        wait_cycles = 0;
        first_tile_preloaded = 1'b0;
        while (!first_tile_preloaded) begin
            @(posedge i_clk);
            first_tile_preloaded = 1'b1;

            for (int lane = 0; lane < CASE_S; lane++) begin
                if (a_feed_count[lane] < CASE_K)
                    first_tile_preloaded = 1'b0;
                if (b_feed_count[lane] < CASE_K)
                    first_tile_preloaded = 1'b0;
            end

            wait_cycles++;
            if (wait_cycles > TEST_TIMEOUT)
                $fatal(1, "[Stage13.12] timeout preloading first tile");
        end

        @(negedge i_clk);
        test_active = 1'b1;
        i_start     = 1'b1;
        @(negedge i_clk);
        i_start     = 1'b0;

        // o_done means producer completion, not necessarily host-drain completion.
        wait_cycles = 0;
        while (!seen_done) begin
            @(posedge i_clk);
            wait_cycles++;
            if (wait_cycles > TEST_TIMEOUT)
                $fatal(1, "[Stage13.12] timeout waiting for o_done");
        end

        // Keep reading until all Python golden words have been observed.
        wait_cycles = 0;
        while ((expected_q.size() != 0) || (result_count < C_WORDS)) begin
            @(posedge i_clk);
            wait_cycles++;
            if (wait_cycles > TEST_TIMEOUT)
                $fatal(1, "[Stage13.12] timeout draining output FIFO");
        end

        repeat (3) @(posedge i_clk);

        if (!seen_busy)
            report_error("o_busy was never observed during the test");

        if (done_count != 1)
            report_error($sformatf("o_done count=%0d expected=1", done_count));

        if (result_count != C_WORDS)
            report_error($sformatf(
                "result count=%0d expected=%0d", result_count, C_WORDS));

        if (expected_q.size() != 0)
            report_error($sformatf(
                "expected queue still contains %0d word(s)", expected_q.size()));

        if (!o_result_empty)
            report_error("output FIFO not empty after final host drain");

        if (accepted_a_writes != expected_a_writes)
            report_error($sformatf(
                "accepted A writes=%0d expected=%0d",
                accepted_a_writes, expected_a_writes));

        if (accepted_b_writes != expected_b_writes)
            report_error($sformatf(
                "accepted B writes=%0d expected=%0d",
                accepted_b_writes, expected_b_writes));

        for (int lane = 0; lane < S_MAX; lane++) begin
            if (a_stream_q[lane].size() != 0)
                report_error($sformatf(
                    "A software queue lane %0d still has %0d word(s)",
                    lane, a_stream_q[lane].size()));

            if (b_stream_q[lane].size() != 0)
                report_error($sformatf(
                    "B software queue lane %0d still has %0d word(s)",
                    lane, b_stream_q[lane].size()));
        end

        feeder_enabled = 1'b0;
        reader_enabled = 1'b0;
        test_active     = 1'b0;

        if (total_errors == errors_at_start) begin
            $display("\nPASS Stage13.12");
            $display("  Results checked : %0d", result_count);
            $display("  A words written : %0d", accepted_a_writes);
            $display("  B words written : %0d", accepted_b_writes);
            $display("  Golden source   : Python .hex only");
            $finish;
        end
        else begin
            $fatal(1,
                "Stage13.12 FAILED: %0d new error(s)",
                total_errors - errors_at_start);
        end
    end

endmodule
